Problema: Com a nova forma de entregar a DIRF somente via ESOCIAL, criei uma query em que é possível validar o cadastro completo dos eventos dos colaboradores,
verificando quais eventos foram usados na folha de pagamento deles para ser realizada a retificação dentro do Esocial.
SQL ANYWHERE

  
SELECT
    id_grupo_eventos             = param.company_event_group_id,
    id_empresa                   = comp.company_id,
    nome_empresa                 = comp.company_name,
    codigo_evento                = evt.event_code,
    nome_evento                  = evt.event_name,       
    valor_total_informado        = SUM(pm.reported_value),
    valor_total_calculado        = SUM(pm.calculated_value),
    codigo_natureza_folha        = evt.monthly_payroll_nature,
    CASE                                                            --- SISTEMA NÃO POSSUI TABELA PARA DESCRIÇÃO DE NATUREZA DE RUBRICA, SENDO NECESSÁRIO COLOCAR MANUALMENTE NO CASE
        WHEN evt.monthly_payroll_nature = '1000' THEN 'Salário, vencimento, soldo'
        WHEN evt.monthly_payroll_nature = '1001' THEN 'Subsídio'
        WHEN evt.monthly_payroll_nature = '1002' THEN 'Descanso semanal remunerado - DSR'
        WHEN evt.monthly_payroll_nature = '1003' THEN 'Horas extraordinárias'
        WHEN evt.monthly_payroll_nature = '1004' THEN 'Horas extraordinárias - Banco de horas'
        WHEN evt.monthly_payroll_nature = '1005' THEN 'Direito de arena'
        WHEN evt.monthly_payroll_nature = '1006' THEN 'Intervalos intra e inter jornadas não concedidos'
        WHEN evt.monthly_payroll_nature = '1007' THEN 'Luvas e premiações'
        WHEN evt.monthly_payroll_nature = '1009' THEN 'Salário família - complemento'
        WHEN evt.monthly_payroll_nature = '1010' THEN 'Salário in natura - pagos em bens ou serviços'
        WHEN evt.monthly_payroll_nature = '1011' THEN 'Sobreaviso e prontidão'
        WHEN evt.monthly_payroll_nature = '1012' THEN 'Descanso semanal remunerado - DSR e feriado'
        WHEN evt.monthly_payroll_nature = '1015' THEN 'Adiantamento de férias'
        WHEN evt.monthly_payroll_nature = '1016' THEN 'Férias'
        WHEN evt.monthly_payroll_nature = '1017' THEN 'Terço constitucional de férias'
        WHEN evt.monthly_payroll_nature = '1018' THEN 'Férias - Abono ou gratificação de férias superior a 20 dias'
        WHEN evt.monthly_payroll_nature = '1019' THEN 'Terço constitucional de férias - Abono ou gratificação de férias superior a 20 d'
        WHEN evt.monthly_payroll_nature = '1020' THEN 'Férias'
        WHEN evt.monthly_payroll_nature = '1021' THEN 'Férias - abono ou gratificação de férias superior a 20 dias'
        WHEN evt.monthly_payroll_nature = '1022' THEN 'Férias - abono ou gratificação de férias não excedente a 20 dias'
        WHEN evt.monthly_payroll_nature = '1023' THEN 'Férias - abono pecuniário'
        WHEN evt.monthly_payroll_nature = '1024' THEN 'Férias - o dobro na vigência do contrato'
        WHEN evt.monthly_payroll_nature = '1040' THEN 'Licença-prêmio'
        WHEN evt.monthly_payroll_nature = '1041' THEN 'Licença-prêmio indenizada'
        WHEN evt.monthly_payroll_nature = '1050' THEN 'Remuneração de dias de afastamento'
        WHEN evt.monthly_payroll_nature = '1080' THEN 'Stock Option'
        WHEN evt.monthly_payroll_nature = '1099' THEN 'Outras verbas salariais'
        WHEN evt.monthly_payroll_nature = '1201' THEN 'Adicional de função / cargo confiança'
        WHEN evt.monthly_payroll_nature = '1202' THEN 'Adicional de insalubridade'
        WHEN evt.monthly_payroll_nature = '1203' THEN 'Adicional de periculosidade'
        WHEN evt.monthly_payroll_nature = '1204' THEN 'Adicional de transferência'
        WHEN evt.monthly_payroll_nature = '1205' THEN 'Adicional noturno'
        WHEN evt.monthly_payroll_nature = '1206' THEN 'Adicional por tempo de serviço'
        WHEN evt.monthly_payroll_nature = '1207' THEN 'Comissões, porcentagens, produção'
        WHEN evt.monthly_payroll_nature = '1208' THEN 'Gueltas ou gorjetas - repassadas por fornecedores ou clientes'
        WHEN evt.monthly_payroll_nature = '1209' THEN 'Gueltas ou gorjetas - repassadas pelo empregador'
        WHEN evt.monthly_payroll_nature = '1210' THEN 'Gratificação por acordo ou convenção coletiva'
        WHEN evt.monthly_payroll_nature = '1211' THEN 'Gratificações'
        WHEN evt.monthly_payroll_nature = '1212' THEN 'Gratificação ou outras verbas de natureza permanente'
        WHEN evt.monthly_payroll_nature = '1213' THEN 'Gratificação ou outras verbas de natureza transitória'
        WHEN evt.monthly_payroll_nature = '1214' THEN 'Adicional de penosidade'
        WHEN evt.monthly_payroll_nature = '1215' THEN 'Adicional de Unidocência'
        WHEN evt.monthly_payroll_nature = '1216' THEN 'Adicional de localidade'
        WHEN evt.monthly_payroll_nature = '1217' THEN 'Gratificação de curso/concurso'
        WHEN evt.monthly_payroll_nature = '1225' THEN 'Quebra de caixa'
        WHEN evt.monthly_payroll_nature = '1230' THEN 'Remuneração do dirigente sindical'
        WHEN evt.monthly_payroll_nature = '1299' THEN 'Outros adicionais'
        WHEN evt.monthly_payroll_nature = '1300' THEN 'PLR - Participação em Lucros ou Resultados'
        WHEN evt.monthly_payroll_nature = '1350' THEN 'Bolsa de estudo - estagiário'
        WHEN evt.monthly_payroll_nature = '1351' THEN 'Bolsa de estudo - médico residente'
        WHEN evt.monthly_payroll_nature = '1352' THEN 'Bolsa de estudo ou pesquisa'
        WHEN evt.monthly_payroll_nature = '1401' THEN 'Abono'
        WHEN evt.monthly_payroll_nature = '1402' THEN 'Abono PIS / PASEP'
        WHEN evt.monthly_payroll_nature = '1403' THEN 'Abono legal'
        WHEN evt.monthly_payroll_nature = '1404' THEN 'Auxílio babá'
        WHEN evt.monthly_payroll_nature = '1405' THEN 'Assistência médica'
        WHEN evt.monthly_payroll_nature = '1406' THEN 'Auxílio creche'
        WHEN evt.monthly_payroll_nature = '1407' THEN 'Auxílio educação'
        WHEN evt.monthly_payroll_nature = '1409' THEN 'Salário família'
        WHEN evt.monthly_payroll_nature = '1410' THEN 'Auxílio - Locais de difícil acesso'
        WHEN evt.monthly_payroll_nature = '1411' THEN 'Auxílio-natalidade'
        WHEN evt.monthly_payroll_nature = '1412' THEN 'Abono permanência'
        WHEN evt.monthly_payroll_nature = '1601' THEN 'Ajuda de custo - aeronauta'
        WHEN evt.monthly_payroll_nature = '1602' THEN 'Ajuda de custo de transferência'
        WHEN evt.monthly_payroll_nature = '1603' THEN 'Ajuda de custo paga ao trabalhador'
        WHEN evt.monthly_payroll_nature = '1604' THEN 'Ajuda de custo - acima de 50% da remuneração mensal'
        WHEN evt.monthly_payroll_nature = '1619' THEN 'Ajuda compensatória - Programa Emergencial de Manutenção do Emprego e r'
        WHEN evt.monthly_payroll_nature = '1620' THEN 'Ressarcimento de despesas pelo uso de veículo próprio'
        WHEN evt.monthly_payroll_nature = '1621' THEN 'Ressarcimento de despesas de viagem, exceto despesas com veículos'
        WHEN evt.monthly_payroll_nature = '1623' THEN 'Ressarcimento de provisão'
        WHEN evt.monthly_payroll_nature = '1629' THEN 'Ressarcimento de outras despesas'
        WHEN evt.monthly_payroll_nature = '1650' THEN 'Diárias de viagem'
        WHEN evt.monthly_payroll_nature = '1651' THEN 'Diárias de viagem - até 50% do salário'
        WHEN evt.monthly_payroll_nature = '1652' THEN 'Diárias de viagem - acima de 50% do salário'
        WHEN evt.monthly_payroll_nature = '1799' THEN 'Alimentação concedida em pecúnia com caráter indenizatório'
        WHEN evt.monthly_payroll_nature = '1800' THEN 'Alimentação concedida em pecúnia com caráter salarial'
        WHEN evt.monthly_payroll_nature = '1801' THEN 'Alimentação'
        WHEN evt.monthly_payroll_nature = '1802' THEN 'Etapas (Marítimos)'
        WHEN evt.monthly_payroll_nature = '1805' THEN 'Moradia'
        WHEN evt.monthly_payroll_nature = '1806' THEN 'Alimentação em ticket ou cartão, vinculada ao PAT'
        WHEN evt.monthly_payroll_nature = '1807' THEN 'Alimentação em ticket ou cartão, não vinculada ao PAT'
        WHEN evt.monthly_payroll_nature = '1808' THEN 'Cesta básica ou refeição, vinculada ao PAT'
        WHEN evt.monthly_payroll_nature = '1809' THEN 'Cesta básica ou refeição, não vinculada ao PAT'
        WHEN evt.monthly_payroll_nature = '1810' THEN 'Vale-transporte ou auxílio-transporte com caráter indenizatório'
        WHEN evt.monthly_payroll_nature = '1811' THEN 'Auxílio-transporte ou auxílio-combustível com caráter salarial'
        WHEN evt.monthly_payroll_nature = '1899' THEN 'Outros auxílios'
        WHEN evt.monthly_payroll_nature = '1901' THEN 'Juros e/ou atualização monetária'
        WHEN evt.monthly_payroll_nature = '2501' THEN 'Prêmios'
        WHEN evt.monthly_payroll_nature = '2502' THEN 'Liberalidades concedidas em mais de duas parcelas anuais'
        WHEN evt.monthly_payroll_nature = '2510' THEN 'Direitos autorais e intelectuais'
        WHEN evt.monthly_payroll_nature = '2801' THEN 'Quarentena remunerada'
        WHEN evt.monthly_payroll_nature = '2901' THEN 'Empréstimos'
        WHEN evt.monthly_payroll_nature = '2902' THEN 'Vestuários e equipamentos'
        WHEN evt.monthly_payroll_nature = '2903' THEN 'Vestuário e equipamentos'
        WHEN evt.monthly_payroll_nature = '2920' THEN 'Reembolsos diversos'
        WHEN evt.monthly_payroll_nature = '2930' THEN 'Insuficiência de saldo'
        WHEN evt.monthly_payroll_nature = '2999' THEN 'Arredondamentos'
        WHEN evt.monthly_payroll_nature = '3501' THEN 'Remuneração por prestação de serviços'
        WHEN evt.monthly_payroll_nature = '3505' THEN 'Retiradas (pró labore) de diretores empregados'
        WHEN evt.monthly_payroll_nature = '3506' THEN 'Retiradas (pró labore) de diretores não empregados'
        WHEN evt.monthly_payroll_nature = '3508' THEN 'Retiradas (pró labore) de proprietários ou sócios'
        WHEN evt.monthly_payroll_nature = '3509' THEN 'Honorários a conselheiros'
        WHEN evt.monthly_payroll_nature = '3510' THEN 'Gratificação (jeton)'
        WHEN evt.monthly_payroll_nature = '3511' THEN 'Gratificação eleitoral'
        WHEN evt.monthly_payroll_nature = '3520' THEN 'Remuneração de cooperado'
        WHEN evt.monthly_payroll_nature = '3525' THEN 'Côngruas, prebendas e afins'
        WHEN evt.monthly_payroll_nature = '4010' THEN 'Complementação salarial de auxílio-doença'
        WHEN evt.monthly_payroll_nature = '4011' THEN 'Complemento de salário-mínimo - RPPS'
        WHEN evt.monthly_payroll_nature = '4050' THEN 'Salário maternidade'
        WHEN evt.monthly_payroll_nature = '4051' THEN 'Salário maternidade - 13º salário'
        WHEN evt.monthly_payroll_nature = '5001' THEN '13º salário'
        WHEN evt.monthly_payroll_nature = '5005' THEN '13º salário complementar'
        WHEN evt.monthly_payroll_nature = '5501' THEN 'Adiantamento de salários'
        WHEN evt.monthly_payroll_nature = '5504' THEN '13º salário - Adiantamento'
        WHEN evt.monthly_payroll_nature = '5510' THEN 'Adiantamento de benefícios previdenciários'
        WHEN evt.monthly_payroll_nature = '6000' THEN 'Saldo de salários na rescisão contratual'
        WHEN evt.monthly_payroll_nature = '6001' THEN '13º salário relativo ao aviso-prévio indenizado'
        WHEN evt.monthly_payroll_nature = '6002' THEN '13º salário proporcional na rescisão'
        WHEN evt.monthly_payroll_nature = '6003' THEN 'Indenização compensatória do aviso - prévio'
        WHEN evt.monthly_payroll_nature = '6004' THEN 'Férias - o dobro na rescisão'
        WHEN evt.monthly_payroll_nature = '6006' THEN 'Férias proporcionais'
        WHEN evt.monthly_payroll_nature = '6007' THEN 'Férias vencidas na rescisão'
        WHEN evt.monthly_payroll_nature = '6101' THEN 'Indenização compensatória - multa rescisória 20 ou 40% (CF/88)'
        WHEN evt.monthly_payroll_nature = '6102' THEN 'Indenização do art. 9º da Lei 7.238/1984'
        WHEN evt.monthly_payroll_nature = '6103' THEN 'Indenização do art. 14 da Lei 5.889/1973'
        WHEN evt.monthly_payroll_nature = '6104' THEN 'Indenização do art. 479 da CLT'
        WHEN evt.monthly_payroll_nature = '6105' THEN 'Indenização recebida a título de incentivo a demissão.'
        WHEN evt.monthly_payroll_nature = '6106' THEN 'Multa do art. 477 da CLT.'
        WHEN evt.monthly_payroll_nature = '6107' THEN 'Indenização por quebra de estabilidade'
        WHEN evt.monthly_payroll_nature = '6108' THEN 'Tempo de espera do motorista profissional'
        WHEN evt.monthly_payroll_nature = '6119' THEN 'Indenização rescisória - Programa Emergencial de Manutenção do Emprego e'
        WHEN evt.monthly_payroll_nature = '6129' THEN 'Outras verbas não remuneratórias (indenizatórias ou multas)'
        WHEN evt.monthly_payroll_nature = '6901' THEN 'Desconto do aviso-prévio'
        WHEN evt.monthly_payroll_nature = '6904' THEN 'Multa prevista no art. 480 da CLT'
        WHEN evt.monthly_payroll_nature = '7001' THEN 'Proventos'
        WHEN evt.monthly_payroll_nature = '7002' THEN 'Proventos - Pensão por morte Civil'
        WHEN evt.monthly_payroll_nature = '7003' THEN 'Proventos - Reserva'
        WHEN evt.monthly_payroll_nature = '7004' THEN 'Proventos - Reforma'
        WHEN evt.monthly_payroll_nature = '7005' THEN 'Pensão Militar'
        WHEN evt.monthly_payroll_nature = '7006' THEN 'Auxílio-reclusão'
        WHEN evt.monthly_payroll_nature = '7007' THEN 'Pensões especiais'
        WHEN evt.monthly_payroll_nature = '7008' THEN 'Complementação de aposentadoria/ pensão'
        WHEN evt.monthly_payroll_nature = '9200' THEN 'Desconto de Adiantamentos'
        WHEN evt.monthly_payroll_nature = '9201' THEN 'Contribuição Previdência'
        WHEN evt.monthly_payroll_nature = '9202' THEN 'Contribuição militar'
        WHEN evt.monthly_payroll_nature = '9203' THEN 'Imposto de renda retido na fonte'
        WHEN evt.monthly_payroll_nature = '9205' THEN 'Provisão de contribuição previdenciária'
        WHEN evt.monthly_payroll_nature = '9207' THEN 'Faltas'
        WHEN evt.monthly_payroll_nature = '9208' THEN 'Atrasos'
        WHEN evt.monthly_payroll_nature = '9209' THEN 'Faltas ou atrasos'
        WHEN evt.monthly_payroll_nature = '9210' THEN 'DSR s/faltas e atrasos'
        WHEN evt.monthly_payroll_nature = '9211' THEN 'DSR sobre faltas'
        WHEN evt.monthly_payroll_nature = '9212' THEN 'DSR sobre atrasos'
        WHEN evt.monthly_payroll_nature = '9213' THEN 'Pensão alimentícia'
        WHEN evt.monthly_payroll_nature = '9214' THEN '13º salário - desconto de adiantamento'
        WHEN evt.monthly_payroll_nature = '9216' THEN 'Desconto de vale transporte'
        WHEN evt.monthly_payroll_nature = '9217' THEN 'Contribuição a Outras Entidades e Fundos'
        WHEN evt.monthly_payroll_nature = '9218' THEN 'Retenções judiciais'
        WHEN evt.monthly_payroll_nature = '9219' THEN 'Desconto de assistência médica ou odontológica - Plano coletivo empresarial'
        WHEN evt.monthly_payroll_nature = '9220' THEN 'Alimentação - desconto'
        WHEN evt.monthly_payroll_nature = '9221' THEN 'Desconto de férias'
        WHEN evt.monthly_payroll_nature = '9222' THEN 'Desconto de outros impostos e contribuições'
        WHEN evt.monthly_payroll_nature = '9223' THEN 'Previdência complementar - parte do empregado'
        WHEN evt.monthly_payroll_nature = '9224' THEN 'FAPI - parte do empregado'
        WHEN evt.monthly_payroll_nature = '9225' THEN 'Previdência complementar - parte do servidor'
        WHEN evt.monthly_payroll_nature = '9226' THEN 'Desconto de férias - abono'
        WHEN evt.monthly_payroll_nature = '9230' THEN 'Contribuição sindical laboral'
        WHEN evt.monthly_payroll_nature = '9231' THEN 'Mensalidade sindical ou associativa'
        WHEN evt.monthly_payroll_nature = '9232' THEN 'Contribuição Sindical - Assistencial'
        WHEN evt.monthly_payroll_nature = '9233' THEN 'Contribuição sindical - Confederativa'
        WHEN evt.monthly_payroll_nature = '9240' THEN 'Alimentação concedida em pecúnia - Desconto'
        WHEN evt.monthly_payroll_nature = '9241' THEN 'Alimentação em ticket ou cartão, vinculada ao PAT - Desconto'
        WHEN evt.monthly_payroll_nature = '9242' THEN 'Alimentação em ticket ou cartão, não vinculada ao PAT - Desconto'
        WHEN evt.monthly_payroll_nature = '9243' THEN 'Cesta básica ou refeição, vinculada ao PAT - Desconto'
        WHEN evt.monthly_payroll_nature = '9244' THEN 'Cesta básica ou refeição, não vinculada ao PAT - Desconto'
        WHEN evt.monthly_payroll_nature = '9250' THEN 'Seguro de vida - desconto'
        WHEN evt.monthly_payroll_nature = '9253' THEN 'Empréstimos e Consignado - Desconto'
        WHEN evt.monthly_payroll_nature = '9254' THEN 'Empréstimos consignados - desconto'
        WHEN evt.monthly_payroll_nature = '9255' THEN 'Empréstimo do empregador - desconto'
        WHEN evt.monthly_payroll_nature = '9258' THEN 'Convênios'
        WHEN evt.monthly_payroll_nature = '9260' THEN 'FIES - desconto'
        WHEN evt.monthly_payroll_nature = '9270' THEN 'Danos e prejuízos causados pelo trabalhador'
        WHEN evt.monthly_payroll_nature = '9290' THEN 'Desconto de pagamento indevido em meses anteriores'
        WHEN evt.monthly_payroll_nature = '9291' THEN 'Abate-teto'
        WHEN evt.monthly_payroll_nature = '9292' THEN 'Ressarcimento ao erário'
        WHEN evt.monthly_payroll_nature = '9293' THEN 'Honorários advocatícios'
        WHEN evt.monthly_payroll_nature = '9294' THEN 'Redutor EC 41/03'
        WHEN evt.monthly_payroll_nature = '9299' THEN 'Outros descontos'
        WHEN evt.monthly_payroll_nature = '9901' THEN 'Base de cálculo da contribuição previdenciária'
        WHEN evt.monthly_payroll_nature = '9902' THEN 'Total da Base de cálculo do FGTS'
        WHEN evt.monthly_payroll_nature = '9903' THEN 'Total da Base de cálculo do IRRF'
        WHEN evt.monthly_payroll_nature = '9904' THEN 'Total da Base de cálculo do FGTS rescisório'
        WHEN evt.monthly_payroll_nature = '9905' THEN 'Serviço militar'
        WHEN evt.monthly_payroll_nature = '9906' THEN 'Remuneração no exterior'
        WHEN evt.monthly_payroll_nature = '9907' THEN 'Total da contribuição da previdenciária patronal - RPPS'
        WHEN evt.monthly_payroll_nature = '9908' THEN 'FGTS - depósito'
        WHEN evt.monthly_payroll_nature = '9910' THEN 'Seguros'
        WHEN evt.monthly_payroll_nature = '9911' THEN 'Assistência Médica'
        WHEN evt.monthly_payroll_nature = '9912' THEN 'Desconto de assistência médica ou odontológica - Plano diferente de coletivo'
        WHEN evt.monthly_payroll_nature = '9930' THEN 'Salário maternidade pago pela Previdência Social'
        WHEN evt.monthly_payroll_nature = '9931' THEN '13º salário maternidade pago pela Previdência Social'
        WHEN evt.monthly_payroll_nature = '9932' THEN 'Auxílio - doença acidentário'
        WHEN evt.monthly_payroll_nature = '9933' THEN 'Auxílio-doença'
        WHEN evt.monthly_payroll_nature = '9938' THEN 'Isenção IRRF - 65 anos'
        WHEN evt.monthly_payroll_nature = '9939' THEN 'Outros valores tributáveis'
        WHEN evt.monthly_payroll_nature = '9950' THEN 'Horas extraordinárias - Banco de horas'
        WHEN evt.monthly_payroll_nature = '9951' THEN 'Horas compensadas - Banco de horas'
        WHEN evt.monthly_payroll_nature = '9989' THEN 'Outros valores informativos'
        ELSE 'NAO INFORMADO'
    END AS descricao_natureza_folha,
    incidencia_irrf_esocial      = evt.esocial_irrf_incidence_code,
    incidencia_inss_esocial      = evt.esocial_inss_incidence_code,
    incidencia_fgts_esocial      = evt.esocial_fgts_incidence_code,
    codigo_esocial               = evt.esocial_code

FROM payroll_transactions AS pm
INNER JOIN payroll_parameters AS param ON param.company_id = pm.company_id
INNER JOIN companies AS comp           ON comp.company_id = pm.company_id
INNER JOIN payroll_events AS evt       ON evt.company_event_group_id = param.company_event_group_id 
                                      AND evt.event_code = pm.event_code 
                                      
WHERE pm.transaction_date BETWEEN @start_date AND @end_date --- PERIODO QUE SERÁ INSERIDO PELO USUÁRIO PARA PODER VERIFICAR QUAIS EVENTOS DO SISTEMA FORAM CALCULADOS

GROUP BY
      param.company_event_group_id,
      comp.company_id,
      comp.company_name,
      evt.event_code,
      evt.event_name,
      evt.monthly_payroll_nature,
      evt.esocial_irrf_incidence_code,
      evt.esocial_inss_incidence_code,
      evt.esocial_fgts_incidence_code,
      evt.esocial_code
      
ORDER BY 
      comp.company_id, 
      evt.event_code;
